### ISSUE TITLE
investigate errors on testing Travis CI

### ISSUE THREAD

**Issue by ragingwind** [yeoman/generator-chromeapp#53]
Getting unrecornized errors from master branch

**Comment by kevva** [comment]
`generator.shell` was removed in `0.18.0` https://github.com/yeoman/generator/releases/tag/v0.18.0.

**Comment by ragingwind** [comment]
@kevva thanks. yeah shell and test case has some problem for generator 0.18. I've fixing since come back home but you already got made it. :+1:

**Comment by ragingwind** [comment]
Oops Travis CI still returns an error.

**Comment by kevva** [comment]
Yeah, it doesn't create the manifest.

**Comment by ragingwind** [comment]
directory() was not working properly with sample dir. now It works well
