### ISSUE TITLE
Applying Polymer, gulp and cca 

### ISSUE THREAD

**Issue by ragingwind** [yeoman/generator-chromeapp#54]
Applying Polymer, gulp to Chrome Apps generator, I've played with them for a while. For getting reasonable build task, to make easily and handy, I made a [prototype kit](https://github.com/ragingwind/mobile-chrome-apps-starter-kit) before write a this PR. I think that the prototype kit is suitable to start making new version of the Generator.

What is (big) changes:

- Polymer, Polymer is great. Make Polymer as default in developing Chrome Apps. I embedded Polymer project of polymer generator.
- [Mobile Chrome Apps](https://github.com/MobileChromeApps/mobile-chrome-apps), For preview, We can use `cca run` instead of `livereload` to preview app running on Chrome. Additionally, It is allowed to make a Mobile Chrome Apps using same source.
- Gulp, gulp is primary task system, I made node packages and plugins for gulp (Grunt task is not supported yet, but it's not hard for me. We can support both of them)
- Build task, Users should run build task first to Chrome Apps runs properly while current generator does not require that build task. to use Polymer, [avoiding CSP issue and less vulcanizing Polymer elements, I add build task that makes bundled polymer library, which pre-builded(vulcanized)](https://github.com/ragingwind/mobile-chrome-apps-starter-kit/blob/master/gulpfile.js#L83) is included in user elements. so, once build(vulcanize) no more vulcanize in development version.

The one of my concern is that it would be fine that enforce using cca and Polymer. I need your any comments or any suggestions. how thought? Feel free to advice me. As you know that my Korean writing is much better than in this proposal.

/cc @sindresorhus, @addyosmani @robdodson

**Comment by addyosmani** [comment]
I think it's great you're exploring new territory here. Some thoughts:

- Would Polymer be an option or the default?
- Are you planning on using or upgrading to Polymer 0.8 once its available?
- Does CCA have any limitations compared to livepreview?

**Comment by ragingwind** [comment]
- I like Polymer to be the default. all of tasks has been considered to use Polymer.
- Yes. of course.
- I think, except that users must be installed cca, there are so many benefits. We can run Chrome Apps by command on terminal. I mentioned above, there are many advantages in using cca. see this video if you would know how it works
 - [reload with --watch args](https://www.youtube.com/watch?v=aGmOzrnHjPM)
 - [run Chrome App on emulator and Chrome](https://www.youtube.com/watch?v=8rrkzipnmXQ)

**Comment by robdodson** [comment]
I think this is great, but I think there should be an option for folks who don't want to use Polymer. It's reasonable that some devs would prefer to write their chrome apps using plain HTML

**Comment by ragingwind** [comment]
@robdodson Yes, we can support plain HTML mode as option, Using with `--no-polymer` flags, which is like --coffee option

**Comment by BrunoVernay** [comment]
Any news on this front ?  Any experimental branch?
There are also some recent developments: http://codingwithgerwin.blogspot.fr/2015/07/live-reload-for-polymer-chrome-apps.html
Thanks

**Comment by ragingwind** [comment]
@BrunoVernay I've been working for this for a while. Unfortunately, It still has some problems. I will let you now If I have any progress.

**Comment by ragingwind** [comment]
I'll close this issue because I could have any progress for this.
