### ISSUE TITLE
`grunt debug` doesn't update output files

### ISSUE THREAD

**Issue by alinnert** [yeoman/generator-chromeapp#60]
I've created a new project and I can successfully run it as a chrome app. Then I type `grunt debug` and it starts watching file changes. When I change a file it get's detected correctly (command line says something like `file "..." changed...` and after a very short time `Completed`). But the output files don't get updated.

I've tried to put a unique sample string into `index.html` and used a software to find that text in any file of the entire project. But unless the original file none does contain the text I've entered. That means that no files get updated.

I'm working on a Windows machine and node.js 4.
What can I do to at least identify the source of the problem? Thank you for any help

**Comment by ragingwind** [comment]
Did you check the console log message on the inspect view of the apps?

**Comment by alinnert** [comment]
Oh wow... I was typing more details until I found the problem: I have to launch the app from the `app` folder, not the `dist` folder, right? I've expected the `watch` task to compile everything into the `dist` folder. When I launch the app from `app` everything works.

I think this detail is missing from the docs or getting started guide. Actually it's just a GIF and I can't really tell what exactly is going on there.

**Comment by ragingwind** [comment]
most of case, Preview mode(debug) is for development version not production(dist). If you feel it's lack of content please make it sure. PR always welcome
