### ISSUE TITLE
npm error: generator-chromeapp@0.2.19 requires a peer of generator-mocha@>=0.1.6 but none was installed

### ISSUE THREAD

**Issue by arkdelkaos** [yeoman/generator-chromeapp#61]
I don't know how to bypass this error :( I tried installing the last generator-mocha, even getting the 0.1.6 one myself, but I still have the same problem.
```
$ npm install -g generator-chromeapp
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
/usr/local/lib
├── generator-chromeapp@0.2.19
└── UNMET PEER DEPENDENCY generator-mocha@>=0.1.6

npm WARN EPEERINVALID generator-chromeapp@0.2.19 requires a peer of generator-mocha@>=0.1.6 but none was installed.
```
node 5.3.0

**Comment by ragingwind** [comment]
Check version for yo and npm first and reinstall all of generators after `npm clean cache`

**Comment by arkdelkaos** [comment]
Still the same :(
```
$ npm list -g --depth=0
/usr/local/lib
├── generator-mocha@0.2.0
├── n@2.0.2
├── npm@3.3.12
├── tldr@1.3.0
└── yo@1.5.1
```

**Comment by arkdelkaos** [comment]
Mmm...it happens the same with generator-angular, and I see that tis happens to more people, so I'll bother them ;) Thanks anyway! If I get a solution i'll share it here :)

**Comment by arkdelkaos** [comment]
Ok, so is a npm3 related problem.
YO devs doesn't seems to like npm3 right now (they say it slow), and so they didn't change yo nether generator-angular with the 'new' specs:
> We currently use peerDependencies to have external sub-generators installed automatically with the main generator, eg generator-mocha is a peerDependency in generator-webapp and installed with it.

>npm3 will no longer install peerDependencies, which is a very good change, but will impact how we currently use it:

  >>We will also be changing the behavior of peerDependencies in npm@3. We won’t be automatically downloading the peer dependency anymore. Instead, we’ll warn you if the peer dependency isn’t already installed. This requires you to resolve peerDependency conflicts yourself, manually, but in the long run this should make it less likely that you’ll end up in a tricky spot with your packages’ dependencies. - http://blog.npmjs.org/post/110924823920/npm-weekly-5

>We should probably have sub-generators in dependencies instead.

So, I have to 'go back' to node 4.2.4 for the time being :(

**Comment by ragingwind** [comment]
@arkdelkaos Thanks for your effort and close the issue now.
