### ISSUE TITLE
NPM issue with installing the generator

### ISSUE THREAD

**Issue by jbeuckm** [yeoman/generator-chromeapp#63]
`Majors-iMac:js innovator$ npm install -g generator-mocha
/usr/local/lib
└── generator-mocha@0.3.0 

Majors-iMac:js innovator$ npm install -g generator-chromeapp
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
/usr/local/lib
├── generator-chromeapp@0.2.19 
└── UNMET PEER DEPENDENCY generator-mocha@>=0.1.6

npm WARN EPEERINVALID generator-chromeapp@0.2.19 requires a peer of generator-mocha@>=0.1.6 but none was installed.
Majors-iMac:js innovator$ node -v
v5.0.0
Majors-iMac:js innovator$ npm -v
3.3.9`

**Comment by davidjosephhayes** [comment]
I have the same issue:

```
$ sudo npm install -g generator-chromeapp
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/usr/lib
├── generator-chromeapp@0.2.19 
└── UNMET PEER DEPENDENCY generator-mocha@>=0.1.6

npm WARN generator-chromeapp@0.2.19 requires a peer of generator-mocha@>=0.1.6 but none was installed.
```

**Comment by davidjosephhayes** [comment]
Ok, so, it will install correctly if you put the dependency on the same line:

`$ sudo npm install -g generator-chromeapp generator-mocha`

**Comment by ragingwind** [comment]
thanks @davidjosephhayes
